### ISSUE TITLE
Generator stopts generating.

### ISSUE THREAD

**Issue by BotAndis** [logicguy1/Discord-Nitro-Generator-and-Checker#25] opened 2021-03-29 14:28 UTC
So after some trouble with the installation I got it everything working, but now my problem is that the gen/checker just stops generating after some time. No matter if I use the generator without or with discord hook, I don't get the message that the code is invalid after about 2-15 minutes and then nothing happens anymore. I have tested it in the range of 1k to a million "wanted to be generated codes" and I have had the same problem every time and the program has simply stopped generating codes.
The program works fine with small numbers 10-100. Also, I have no potato PC...

For me, it was just installing and launching the Program with or without discord hook.

Screenshot:
![grafik](https://user-images.githubusercontent.com/59452948/112850170-1240aa80-90aa-11eb-8a3c-f03004dbb71e.png)

**Expected behavior**
 It just stops generating keys. There are no results...

 - OS: Windows
 - Version 20H2

**Comment by logicguy1** [comment] 2021-03-30 07:27
Hello thank you for your issue, this is a current bug i am going to be fixing over the cause of the next day or so

**Comment by pablothespanishguy** [comment] 2021-04-11 16:01
Close this. @logicguy1

**Closed** 2021-04-11 16:05 UTC
Labels: bug
